%YAML:1.0
################################################################################
# Copyright (c) 2020-2021, NVIDIA CORPORATION. All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
################################################################################

BaseConfig:
  minDetectorConfidence: 0.25    # If the confidence of a detector bbox is lower than this, then it won't be considered for tracking

TargetManagement:
  enableBboxUnClipping: 1    # In case the bbox is likely to be clipped by image border, unclip bbox
  maxTargetsPerStream: 200   # Increased for multi-camera tracking with ReID
  
  # [Creation & Termination Policy]
  minIouDiff4NewTarget: 0.5  # If the IOU between the newly detected object and any of the existing targets is higher than this threshold, this newly detected object will be discarded.
  minTrackerConfidence: 0.2  # If the confidence of an object tracker is lower than this on the fly, then it will be tracked in shadow mode. Valid Range: [0.0, 1.0]
  probationAge: 3            # If the target's age exceeds this, the target will be considered to be valid.
  maxShadowTrackingAge: 90   # Extended for cross-camera gaps and occlusions
  earlyTerminationAge: 1     # If the trackingAge does not exceed this, the target will be terminated early.

TrajectoryManagement:
  useUniqueID: 1             # Use 64-bit long Unique ID when assignTrackerId is set to false. Default is [true]
  enableReAssoc: 1           # Enable Re-Assoc

DataAssociator:
  dataAssociatorType: 0      # the type of data associator among { DEFAULT= 0 }
  associationMatcherType: 0  # the type of matching algorithm among { GREEDY=0, CASCADED=1 }
  checkClassMatch: 1         # If checked, only the same-class objects are associated with each other. Default: true

  # [Association Metric: Thresholds for valid candidates]
  minMatchingScore4Overall: 0.0    # Min total score
  minMatchingScore4SizeAndShape: 0.6    # Min bbox size/shape score
  minMatchingScore4Appearance: 0.4      # Min appearance score
  minMatchingScore4Motion: 0.2          # Min motion score

StateEstimator:
  stateEstimatorType: 1      # the type of state estimator among { DUMMY=0, SIMPLE=1, REGULAR=2 }

  # [Dynamics Modeling]
  processNoiseVar4Loc: 2.0   # Process noise variance for bbox center
  processNoiseVar4Size: 1.0  # Process noise variance for bbox size
  processNoiseVar4Vel: 0.1   # Process noise variance for velocity
  measurementNoiseVar4Detector: 4.0    # Measurement noise variance for detector bbox
  measurementNoiseVar4Tracker: 16.0    # Measurement noise variance for tracker bbox

ReID:
  reidType: 2     # Enable Reid based reassociation for multi-camera tracking
  batchSize: 100  # Batch size of reid network
  workspaceSize: 1000    # Workspace size to be used by reid engine, in MB
  reidFeatureSize: 256   # Size of reid feature
  reidHistorySize: 100   # Max number of reid features kept for one object
  inferDims: [256, 128, 3]   # H, W, C
  networkMode: 1    # FP16 precision for performance
  inputOrder: 0     # NCHW format for optimal performance
  reidExtractionInterval: 0  # Extract features every frame for continuous tracking
  addFeatureNormalization: 1 # L2 normalize features for better matching
  keepAspc: 1      # Maintain aspect ratio when resizing
  netScaleFactor: 0.01735207  # Normalization factor for ReID network

FeatureMatching:
  featureMatchingAlgorithm: 1 # Hungarian algorithm for optimal assignment
  matchingThreshold: 0.75     # Increased threshold for better cross-camera matching
  trajectorySetSize: 50       # Increased for multi-camera tracking scenarios